import type { Movie } from '@/lib/types';

export const movies: Movie[] = [
  {
    id: 'interstellar',
    title: 'Interstellar',
    description: 'Dans un futur proche, face à une Terre exsangue, un groupe d’explorateurs utilise un vaisseau interstellaire pour franchir un trou de ver permettant de parcourir des distances jusque‐là infranchissables.',
    longDescription: 'Dans un futur proche, face à une Terre exsangue, un groupe d’explorateurs utilise un vaisseau interstellaire pour franchir un trou de ver permettant de parcourir des distances jusque‐là infranchissables. Leur but : trouver un nouveau foyer pour l’humanité.',
    genres: ['Aventure', 'Drame', 'Science-Fiction'],
    year: 2014,
    rating: 8.5,
    imageId: 'interstellar-poster',
    videoUrl: 'https://cinecake.xyz/movies/Interstellar.mp4',
  },
  {
    id: 'the-dark-knight',
    title: 'The Dark Knight : Le Chevalier noir',
    description: 'Batman aborde une phase décisive de sa guerre contre le crime à Gotham City.',
    longDescription: 'Batman aborde une phase décisive de sa guerre contre le crime à Gotham City. Avec l\'aide du lieutenant de police Jim Gordon et du nouveau procureur Harvey Dent, il entreprend de démanteler les dernières organisations criminelles qui infestent les rues de la ville. L\'association s\'avère efficace, mais le trio se heurte bientôt à un nouveau génie',
    genres: ['Action', 'Crime', 'Drame', 'Thriller'],
    year: 2008,
    rating: 8.5,
    imageId: 'the-dark-knight-poster',
    videoUrl: 'https://cinecake.xyz/movies/The-Dark-Knight-Le-Chevalier-noir.mp4',
  },
  {
    id: 'scream',
    title: 'Scream',
    description: 'Casey Becker, une belle adolescente, est seule dans la maison familiale. Elle s\'apprête à regarder un film d\'horreur, mais le téléphone sonne.',
    longDescription: 'Casey Becker, une belle adolescente, est seule dans la maison familiale. Elle s\'apprête à regarder un film d\'horreur, mais le téléphone sonne. Au bout du fil, un serial killer la malmène, et la force à jouer à un jeu terrible : si elle répond mal à ses questions portant sur les films d\'horreur, celui-ci tuera son copain… Sidney Prescott sait qu\'elle est l\'une des',
    genres: ['Crime', 'Horreur', 'Mystère'],
    year: 1996,
    rating: 7.4,
    imageId: 'scream-poster',
    videoUrl: 'https://cinecake.xyz/movies/Scream.mp4',
  },
  {
    id: 'space-jam',
    title: 'Space Jam',
    description: 'Bugs Bunny et ses amis font appel à une légende du basket pour défier une équipe d\'extraterrestres sur le terrain.',
    longDescription: 'Bugs Bunny et ses amis font appel à une légende du basket pour défier une équipe d\'extraterrestres sur le terrain.',
    genres: ['Aventure', 'Animation', 'Comédie', 'Familial', 'Science-Fiction'],
    year: 1996,
    rating: 6.8,
    imageId: 'space-jam-poster',
    videoUrl: 'https://cinecake.xyz/movies/Space-Jam.mp4',
  },
  {
    id: 'gran-turismo',
    title: 'Gran Turismo',
    description: 'Gran Turismo est inspiré de l\'incroyable histoire vécue d\'une invraisemblable bande d\'infortunés.',
    longDescription: 'Gran Turismo est inspiré de l\'incroyable histoire vécue d\'une invraisemblable bande d\'infortunés – un amateur de jeu vidéo de classe ouvrière, un ex-pilote d\'autos de course paumé et un idéaliste de l\'industrie du sport motorisé. Ensemble, ils risquent tout pour percer dans le sport le plus prestigieux au monde. Gran Turismo est une captivante',
    genres: ['Action', 'Aventure', 'Drame'],
    year: 2023,
    rating: 7.7,
    imageId: 'gran-turismo-poster',
    videoUrl: 'https://cinecake.xyz/movies/Gran-Turismo.mp4',
  },
  {
    id: 'rogue-one-a-star-wars-story',
    title: 'Rogue One : A Star Wars Story',
    description: 'Situé entre les épisodes III et IV de la saga Star Wars, le film nous entraîne aux côtés d’individus ordinaires qui, pour rester fidèles à leurs valeurs, vont tenter l’impossible au péril de leur vie.',
    longDescription: 'Situé entre les épisodes III et IV de la saga Star Wars, le film nous entraîne aux côtés d’individus ordinaires qui, pour rester fidèles à leurs valeurs, vont tenter l’impossible au péril de leur vie. Ils n’avaient pas prévu de devenir des héros, mais dans une époque de plus en plus sombre, ils vont devoir dérober les plans de l’Étoile de la Mort, l’arme de',
    genres: ['Action', 'Aventure', 'Science-Fiction'],
    year: 2016,
    rating: 7.5,
    imageId: 'rogue-one-a-star-wars-story-poster',
    videoUrl: 'https://cinecake.xyz/movies/Rogue-One-A-Star-Wars-Story.mp4',
  },
  {
    id: 'gladiator',
    title: 'Gladiator',
    description: 'Le général romain Maximus est le plus fidèle soutien de l\'empereur Marc Aurèle, qu\'il a conduit de victoire en victoire avec une bravoure et un dévouement exemplaires.',
    longDescription: 'Le général romain Maximus est le plus fidèle soutien de l\'empereur Marc Aurèle, qu\'il a conduit de victoire en victoire avec une bravoure et un dévouement exemplaires. Jaloux du prestige de Maximus, et plus encore de l\'amour que lui voue l\'empereur, le fils de Marc Aurèle, Commode, s\'arroge brutalement le pouvoir, puis ordonne l\'arrestation du général et son exécution. Maximus échappe à ses assassins mais ne peut empêcher le',
    genres: ['Action', 'Aventure', 'Drame'],
    year: 2000,
    rating: 8.2,
    imageId: 'gladiator-poster',
    videoUrl: 'https://cinecake.xyz/movies/Gladiator.mp4',
  },
  {
    id: 'matrix',
    title: 'Matrix',
    description: 'Programmeur anonyme dans un service administratif le jour, Thomas Anderson devient Neo la nuit venue.',
    longDescription: 'Programmeur anonyme dans un service administratif le jour, Thomas Anderson devient Neo la nuit venue. Sous ce pseudonyme, il est l\'un des pirates les plus recherchés du cyber‐espace. À cheval entre deux mondes, Neo est assailli par d\'étranges songes et des messages cryptés provenant d\'un certain Morpheus. Celui‐ci l\'exhorte à aller au‐delà des apparences et à trouver la réponse à la question qui hante constamment ses pensées',
    genres: ['Action', 'Science-Fiction'],
    year: 1999,
    rating: 8.2,
    imageId: 'matrix-poster',
    videoUrl: 'https://cinecake.xyz/movies/Matrix.mp4',
  },
  {
    id: 'titanic',
    title: 'Titanic',
    description: 'Southampton, 10 avril 1912. Le paquebot le plus grand et le plus moderne du monde, réputé pour son insubmersibilité, le « Titanic », appareille pour son premier voyage.',
    longDescription: 'Southampton, 10 avril 1912. Le paquebot le plus grand et le plus moderne du monde, réputé pour son insubmersibilité, le « Titanic », appareille pour son premier voyage. Quatre jours plus tard, il heurte un iceberg. À son bord, un artiste pauvre et une grande bourgeoise tombent amoureux.',
    genres: ['Drame', 'Romance'],
    year: 1997,
    rating: 7.9,
    imageId: 'titanic-poster',
    videoUrl: 'https://cinecake.xyz/movies/Titanic.mp4',
  },
  {
    id: 'top-gun-maverick',
    title: 'Top Gun : Maverick',
    description: 'Après avoir été l’un des meilleurs pilotes de chasse de l\'Aéronavale américaine pendant plus de trente ans, Pete “Maverick" Mitchell continue à repousser ses limites en tant que pilote d\'essai.',
    longDescription: 'Après avoir été l’un des meilleurs pilotes de chasse de l\'Aéronavale américaine pendant plus de trente ans, Pete “Maverick" Mitchell continue à repousser ses limites en tant que pilote d\'essai. Il refuse de monter en grade, car cela l’obligerait à renoncer à voler. Il est chargé de former un détachement de jeunes diplômés de l’école Top Gun pour une',
    genres: ['Action', 'Drame'],
    year: 2022,
    rating: 8.2,
    imageId: 'top-gun-maverick-poster',
    videoUrl: 'https://cinecake.xyz/movies/Top-Gun-Maverick.mp4',
  },
  {
    id: 'oppenheimer',
    title: 'Oppenheimer',
    description: 'En 1942, convaincus que l\'Allemagne hitlérienne est en train de développer une arme nucléaire, les États-Unis initient, dans le plus grand secret, le « Projet Manhattan » destiné à mettre au point la première bombe atomique de l’histoire.',
    longDescription: 'En 1942, convaincus que l\'Allemagne hitlérienne est en train de développer une arme nucléaire, les États-Unis initient, dans le plus grand secret, le « Projet Manhattan » destiné à mettre au point la première bombe atomique de l’histoire. Pour piloter ce dispositif, le gouvernement engage J. Robert Oppenheimer, brillant physicien, qui sera bientôt surnommé « le père de la bombe atomique ». C\'est dans le laboratoire ultra-',
    genres: ['Drame', 'Histoire'],
    year: 2023,
    rating: 8.1,
    imageId: 'oppenheimer-poster',
    videoUrl: 'https://cinecake.xyz/movies/Oppenheimer.mp4',
  },
  {
    id: 'zack-snyders-justice-league',
    title: 'Zack Snyder\'s Justice League',
    description: 'Bruce Wayne est déterminé à faire en sorte que le sacrifice ultime de Superman ne soit pas vain.',
    longDescription: 'Bruce Wayne est déterminé à faire en sorte que le sacrifice ultime de Superman ne soit pas vain. Pour cela, avec l\'aide de Diana Prince, il met en place un plan pour recruter une équipe de métahumains afin de protéger le monde d\'une menace apocalyptique imminente. La tâche s\'avère plus difficile qu\'il ne l\'imaginait, car chacune des recrues',
    genres: ['Action', 'Aventure', 'Fantastique'],
    year: 2021,
    rating: 8.1,
    imageId: 'zack-snyders-justice-league-poster',
    videoUrl: 'https://cinecake.xyz/movies/Zack-Snyders-Justice-League.mp4',
  },
  {
    id: 'shazam-la-rage-des-dieux',
    title: 'Shazam! La Rage des Dieux',
    description: 'Investis des pouvoirs des dieux, Billy Batson et ses copains apprennent encore à concilier leur vie d’ados avec leurs responsabilités de super-héros.',
    longDescription: 'Investis des pouvoirs des dieux, Billy Batson et ses copains apprennent encore à concilier leur vie d’ados avec leurs responsabilités de super-héros dès lors qu’ils se transforment en adultes. Mais quand les Filles de l’Atlas, trio d’anciennes déesses ivres de vengeance, débarquent sur Terre pour retrouver la magie qu’on leur a volée il y a longtemps, Billy,',
    genres: ['Action', 'Comédie', 'Fantastique'],
    year: 2023,
    rating: 6.5,
    imageId: 'shazam-la-rage-des-dieux-poster',
    videoUrl: 'https://cinecake.xyz/movies/Shazam-La-Rage-des-dieux.mp4',
  },
  {
    id: 'space-jam-nouvelle-ere',
    title: 'Space Jam : Nouvelle Ère',
    description: 'LeBron et son jeune fils Dom sont retenus prisonniers dans un espace numérique par une intelligence artificielle malveillante.',
    longDescription: 'LeBron et son jeune fils Dom sont retenus prisonniers dans un espace numérique par une intelligence artificielle malveillante. Le joueur de basket doit ramener son petit garçon sain et sauf chez lui, en faisant triompher Bugs, Lola Bunny et leurs camarades Looney Tunes, réputés pour leur esprit frondeur, face aux champions numérisés de l\'IA.',
    genres: ['Aventure', 'Animation', 'Comédie', 'Familial', 'Science-Fiction'],
    year: 2021,
    rating: 6.7,
    imageId: 'space-jam-nouvelle-ere-poster',
    videoUrl: 'https://cinecake.xyz/movies/Space-Jam-Nouvelle-Ere.mp4',
  },
  {
    id: 'casino-royale',
    title: 'Casino Royale',
    description: 'Pour sa première mission, James Bond affronte le tout-puissant banquier privé du terrorisme international, Le Chiffre.',
    longDescription: 'Pour sa première mission, James Bond affronte le tout-puissant banquier privé du terrorisme international, Le Chiffre. Pour achever de le ruiner et démanteler le plus grand réseau criminel qui soit, Bond doit le battre lors d\'une partie de poker à haut risque au Casino Royale. La très belle Vesper, attachée au Trésor, l\'accompagne afin de veiller à ce',
    genres: ['Action', 'Aventure', 'Thriller'],
    year: 2006,
    rating: 7.6,
    imageId: 'casino-royale-poster',
    videoUrl: 'https://cinecake.xyz/movies/Casino-Royale.mp4',
  },
  {
    id: 'spectre',
    title: 'Spectre',
    description: 'Un message cryptique surgi du passé entraîne James Bond dans une mission très personnelle à Mexico puis à Rome, où il rencontre Lucia Sciarra, la très belle veuve d’un célèbre criminel.',
    longDescription: 'Un message cryptique surgi du passé entraîne James Bond dans une mission très personnelle à Mexico puis à Rome, où il rencontre Lucia Sciarra, la très belle veuve d’un célèbre criminel. Bond réussit à infiltrer une réunion secrète révélant une redoutable organisation baptisée Spectre. Pendant ce temps, à Londres, Max Denbigh, le nouveau',
    genres: ['Action', 'Aventure', 'Thriller'],
    year: 2015,
    rating: 6.6,
    imageId: 'spectre-poster',
    videoUrl: 'https://cinecake.xyz/movies/Spectre.mp4',
  },
  {
    id: 'mourir-peut-attendre',
    title: 'Mourir peut attendre',
    description: 'James Bond a quitté les services secrets et coule des jours heureux en Jamaïque. Mais sa tranquillité est de courte durée...',
    longDescription: 'James Bond a quitté les services secrets et coule des jours heureux en Jamaïque. Mais sa tranquillité est de courte durée car son vieil ami Felix Leiter de la CIA débarque pour solliciter son aide : il s\'agit de sauver un scientifique qui vient d\'être kidnappé. Mais la mission se révèle bien plus dangereuse que prévu et Bond se retrouve aux trousses d\'un mystérieux ennemi détenant de redoutables armes technologiques…',
    genres: ['Action', 'Aventure', 'Thriller'],
    year: 2021,
    rating: 7.4,
    imageId: 'mourir-peut-attendre-poster',
    videoUrl: 'https://cinecake.xyz/movies/Mourir-peut-attendre.mp4',
  },
  {
    id: 'star-wars-episode-i-the-phantom-menace',
    title: 'Star Wars, épisode I - La Menace fantôme',
    description: 'Il y a bien longtemps, dans une galaxie très lointaine... La République connaît de nombreux tourments : la corruption fait vaciller ses bases, le Sénat s\'embourbe dans des discussions politiques sans fin et de nombreux pouvoirs dissidents commencent à émerger, annonçant la chute d\'un système autrefois paisible.',
    longDescription: 'Il y a bien longtemps, dans une galaxie très lointaine... La République connaît de nombreux tourments : la corruption fait vaciller ses bases, le Sénat s\'embourbe dans des discussions politiques sans fin et de nombreux pouvoirs dissidents commencent à émerger, annonçant la chute d\'un système autrefois paisible. Puissante et intouchable,',
    genres: ['Action', 'Aventure', 'Science-Fiction'],
    year: 1999,
    rating: 6.6,
    imageId: 'star-wars-episode-i-the-phantom-menace-poster',
    videoUrl: 'https://cinecake.xyz/movies/Star-Wars-Episode-I-La-Menace-Phantom.mp4',
  },
  {
    id: 'saw',
    title: 'Saw',
    description: 'Deux hommes se réveillent enchaînés au mur d’une salle de bains. Ils ignorent où ils sont et ne se connaissent pas. Ils savent juste que l’un doit absolument tuer l’autre, sinon dans moins de huit heures, ils seront exécutés tous les deux…',
    longDescription: 'Deux hommes se réveillent enchaînés au mur d’une salle de bains. Ils ignorent où ils sont et ne se connaissent pas. Ils savent juste que l’un doit absolument tuer l’autre, sinon dans moins de huit heures, ils seront exécutés tous les deux… Voici l’une des situations imaginées par un machiavélique maître criminel qui impose à ses victimes des choix',
    genres: ['Crime', 'Horreur', 'Mystère'],
    year: 2004,
    rating: 7.4,
    imageId: 'saw-poster',
    videoUrl: 'https://cinecake.xyz/movies/Saw.mp4',
  },
  {
    id: 'spider-man-across-the-spider-verse',
    title: 'Spider-Man : Across the Spider-Verse',
    description: 'Après avoir retrouvé Gwen Stacy, Spider-Man, le sympathique héros originaire de Brooklyn, est catapulté à travers le Multivers, où il rencontre une équipe de Spider-Héros chargée d\'en protéger l\'existence.',
    longDescription: 'Après avoir retrouvé Gwen Stacy, Spider-Man, le sympathique héros originaire de Brooklyn, est catapulté à travers le Multivers, où il rencontre une équipe de Spider-Héros chargée d\'en proteger l\'existence. Mais lorsque les héros s\'opposent sur la façon de gérer une nouvelle menace, Miles se retrouve confronté à eux et doit redéfinir ce que signifie',
    genres: ['Action', 'Aventure', 'Animation', 'Science-Fiction'],
    year: 2023,
    rating: 8.3,
    imageId: 'spider-man-across-the-spider-verse-poster',
    videoUrl: 'https://cinecake.xyz/movies/Spider-Man-Across-The-Spider-Verse.mp4',
  },
  {
    id: 'spider-man-new-generation',
    title: 'Spider-Man : New Generation',
    description: 'Spider-Man : New Generation suit les aventures de Miles Morales, un adolescent afro-américain et portoricain qui vit à Brooklyn et s’efforce de s’intégrer dans son nouveau collège à Manhattan.',
    longDescription: 'Spider-Man : New Generation suit les aventures de Miles Morales, un adolescent afro-américain et portoricain qui vit à Brooklyn et s’efforce de s’intégrer dans son nouveau collège à Manhattan. Mais la vie de Miles se complique quand il se fait mordre par une araignée radioactive et se découvre des super-pouvoirs : il est désormais capable',
    genres: ['Action', 'Aventure', 'Animation', 'Science-Fiction'],
    year: 2018,
    rating: 8.4,
    imageId: 'spider-man-new-generation-poster',
    videoUrl: 'https://cinecake.xyz/movies/Spider-Man-New-Generation.mp4',
  },
  {
    id: 'free-guy',
    title: 'Free Guy',
    description: 'Un employé de banque, découvrant un jour qu’il n’est en fait qu’un personnage d’arrière-plan dans un jeu vidéo en ligne, décide de devenir le héros de sa propre histoire, quitte à la réécrire.',
    longDescription: 'Un employé de banque, découvrant un jour qu’il n’est en fait qu’un personnage d’arrière-plan dans un jeu vidéo en ligne, décide de devenir le héros de sa propre histoire, quitte à la réécrire. Évoluant désormais dans un monde qui ne connaît pas de limites, il va tout mettre en œuvre pour le sauver à sa manière, avant qu’il ne soit trop tard…',
    genres: ['Aventure', 'Comédie', 'Science-Fiction'],
    year: 2021,
    rating: 7.5,
    imageId: 'free-guy-poster',
    videoUrl: 'https://cinecake.xyz/movies/Free-Guy.mp4',
  },
  {
    id: 'dragons',
    title: 'Dragons',
    description: 'Sur l\'île accidentée de Berk, où Vikings et dragons se vouent une haine viscérale depuis des générations, Harold fait figure d\'exception.',
    longDescription: 'Sur l\'île accidentée de Berk, où Vikings et dragons se vouent une haine viscérale depuis des générations, Harold fait figure d\'exception. Fils inventif mais négligé du chef Stoïck la Brute, il bouscule les traditions en se liant d\'amitié avec Krokmou, une Furie nocturne. Leur duo improbable va révéler la vraie nature des dragons et bouleverser les',
    genres: ['Action', 'Familial', 'Fantastique'],
    year: 2025,
    rating: 8.0,
    imageId: 'dragons-poster',
    videoUrl: 'https://cinecake.xyz/movies/Dragon-2025.mp4',
  },
  {
    id: 'minecraft-le-film',
    title: 'Minecraft, le film',
    description: 'Quatre mésadaptés traversent soudainement un portail mystérieux menant à la Surface : un étrange univers cubique qui évolue grâce à l’imagination.',
    longDescription: 'Quatre mésadaptés traversent soudainement un portail mystérieux menant à la Surface : un étrange univers cubique qui évolue grâce à l’imagination. Pour rentrer chez eux, ils se lancent dans une quête magique avec Steve, un surprenant fabricateur expert. L’aventure les poussera à faire preuve d’audace et à renouer avec les qualités qui',
    genres: ['Aventure', 'Comédie', 'Familial', 'Fantastique'],
    year: 2025,
    rating: 6.4,
    imageId: 'minecraft-le-film-poster',
    videoUrl: 'https://cinecake.xyz/movies/Minecraft.mp4',
  },
  {
    id: 'f1-le-film',
    title: 'F1® Le Film',
    description: 'Sonny Hayes était le prodige de la F1 des années 90 jusqu’à son terrible accident. Trente ans plus tard, il doit prouver qu\'il est toujours le meilleur.',
    longDescription: 'Sonny Hayes était le prodige de la F1 des années 90 jusqu’à son terrible accident. Trente ans plus tard, devenu un pilote indépendant, il est contacté par Ruben Cervantes, patron d’une écurie en faillite qui le convainc de revenir pour sauver l’équipe et prouver qu’il est toujours le meilleur. Aux côtés de Joshua Pearce, diamant brut prêt à devenir le numéro un, Sonny doit affronter ses démons et les dangers de la piste pour atteindre la rédemption.',
    genres: ['Action', 'Drame'],
    year: 2025,
    rating: 7.8,
    imageId: 'f1-le-film-poster',
    videoUrl: 'https://cinecake.xyz/movies/F1-The-Movie.mp4',
  },
  {
    id: 'dune-part-one',
    title: 'Dune : Première partie',
    description: "L'histoire de Paul Atreides, jeune homme aussi doué que brillant, voué à connaître un destin hors du commun qui le dépasse totalement. Car, s'il veut préserver l'avenir de sa famille et de son peuple, il devra se rendre sur Dune, la planète la plus dangereuse de l'Univers.",
    longDescription: "L'histoire de Paul Atreides, jeune homme aussi doué que brillant, voué à connaître un destin hors du commun qui le dépasse totalement. Car, s'il veut préserver l'avenir de sa famille et de son peuple, il devra se rendre sur Dune, la planète la plus dangereuse de l'Univers. Mais aussi la seule à même de fournir la ressource la plus précieuse capable de décupler la puissance de l'humanité.",
    genres: ['Aventure', 'Science-Fiction'],
    year: 2021,
    rating: 7.8,
    imageId: 'dune-part-one-poster',
    videoUrl: 'https://cinecake.xyz/movies/Dune-Premiere-partie.mp4',
  },
  {
    id: 'lilo-stitch',
    title: 'Lilo & Stitch',
    description: "Sur l'île d'Hawaï, une petite fille espiègle nommée Lilo adopte ce qu'elle croit être un chien étrange, qu'elle prénomme Stitch.",
    longDescription: "Sur l'île d'Hawaï, une petite fille espiègle nommée Lilo adopte ce qu'elle croit être un chien étrange, qu'elle prénomme Stitch. Mais Stitch est en réalité une créature extraterrestre créée pour semer le chaos. Malgré son tempérament destructeur, il découvre peu à peu les valeurs de l’amitié, de l’amour et de la famille.",
    genres: ['Aventure', 'Comédie', 'Familial', 'Science-Fiction'],
    year: 2025,
    rating: 7.3,
    imageId: 'lilo-stitch-poster',
    videoUrl: 'https://cinecake.xyz/movies/Lilo-Et-Stitch-2025.mp4',
  },
  {
    id: 'dune-part-two',
    title: 'Dune : Deuxième partie',
    description: "Le voyage mythique de Paul Atreides qui s'allie à Chani et aux Fremen dans sa quête de vengeance envers les conspirateurs qui ont anéanti sa famille.",
    longDescription: "Le voyage mythique de Paul Atreides qui s'allie à Chani et aux Fremen dans sa quête de vengeance envers les conspirateurs qui ont anéanti sa famille. Devant choisir entre l'amour de sa vie et le destin de l'univers, il fera tout pour éviter un terrible futur que lui seul peut prédire.",
    genres: ['Aventure', 'Science-Fiction'],
    year: 2024,
    rating: 8.1,
    imageId: 'dune-part-two-poster',
    videoUrl: 'https://cinecake.xyz/movies/Dune-Deuxieme-partie.mp4',
  },
  {
    id: 'lamour-ouf',
    title: 'L\'Amour ouf',
    description: "Les années 80, dans le nord de la France. Jackie et Clotaire grandissent entre les bancs du lycée et les docks du port. Elle étudie, il traîne. Et puis leurs destins se croisent et c'est l'amour fou.",
    longDescription: "Les années 80, dans le nord de la France. Jackie et Clotaire grandissent entre les bancs du lycée et les docks du port. Elle étudie, il traîne. Et puis leurs destins se croisent et c'est l'amour fou. La vie s'efforcera de les séparer mais rien n'y fait, ces deux-là sont comme les deux ventricules du même cœur...",
    genres: ['Crime', 'Drame', 'Romance'],
    year: 2024,
    rating: 7.2,
    imageId: 'lamour-ouf-poster',
    videoUrl: "https://cinecake.xyz/movies/L'Amour-ouf.mp4",
  }
];
