import type { Movie } from '@/lib/types';

export const movies: Movie[] = [
  {
    id: 'f1-le-film',
    title: 'F1® Le Film',
    description: 'Sonny Hayes était le prodige de la F1 des années 90 jusqu’à son terrible accident.',
    longDescription: 'Sonny Hayes était le prodige de la F1 des années 90 jusqu’à son terrible accident. Trente ans plus tard, devenu un pilote indépendant, il est contacté par Ruben Cervantes, patron d’une écurie en faillite qui le convainc de revenir pour sauver l’équipe et prouver qu’il est toujours le meilleur. Aux côtés de Joshua Pearce, diamant brut prêt à devenir le numéro 1, Sonny réalise vite qu\'en F1, son coéquipier est aussi son plus grand rival.',
    genres: ['Action', 'Drame'],
    year: 2025,
    rating: 8.7,
    imageId: 'f1-le-film-poster',
    videoUrl: 'https://cinecake.xyz/movies/F1-The-Movie.mp4',
  },
  {
    id: 'super-mario-bros-le-film',
    title: 'Super Mario Bros. le film',
    description: 'Alors qu’ils tentent de réparer une canalisation souterraine, Mario et son frère Luigi, tous deux plombiers, se retrouvent plongés dans un nouvel univers féerique à travers un mystérieux conduit.',
    longDescription: 'Alors qu’ils tentent de réparer une canalisation souterraine, Mario et son frère Luigi, tous deux plombiers, se retrouvent plongés dans un nouvel univers féerique à travers un mystérieux conduit. Mais lorsque les deux frères sont séparés, Mario s’engage dans une aventure trépidante pour retrouver Luigi. Dans sa quête, il peut compter sur l’aide du champignon Toad, habitant du Royaume Champignon, et les conseils avisés.',
    genres: ['Aventure', 'Animation', 'Comédie', 'Familial', 'Fantastique'],
    year: 2023,
    rating: 7.6,
    imageId: 'super-mario-bros-le-film-poster',
    videoUrl: 'https://cinecake.xyz/movies/Super-Mario-Bros-Le-Film.mp4',
  },
  {
    id: 'mission-impossible-final-reckoning',
    title: 'Mission : Impossible - The Final Reckoning',
    description: 'Ethan Hunt se rend à Londres avec son équipe dans l\'espoir de remonter la piste du mystérieux Gabriel.',
    longDescription: 'Ethan Hunt se rend à Londres avec son équipe dans l\'espoir de remonter la piste du mystérieux Gabriel, qu\'il a affronté deux mois auparavant à bord de l\'Orient-Express et qui détient la clé contrôlant l’intelligence artificielle toute puissante surnommée l\'Entité. Adulée par les uns, redoutée par les autres, l’Entité se distingue par sa capacité à prédire',
    genres: ['Action', 'Aventure', 'Thriller'],
    year: 2025,
    rating: 7.3,
    imageId: 'mission-impossible-final-reckoning-poster',
    videoUrl: 'https://cinecake.xyz/movies/Mission-Impossible-The-Final-Reckoning.mp4',
  },
  {
    id: 'superman',
    title: 'Superman',
    description: 'Superman doit trouver l’équilibre entre ses racines kryptoniennes et son identité humaine...',
    longDescription: 'Superman doit trouver l’équilibre entre ses racines kryptoniennes et son identité humaine, sous les traits de Clark Kent, originaire de Smallville, dans le Kansas. Il est l’incarnation de la vérité, de la justice et des valeurs américaines et il est animé par une véritable bienveillance dans un monde qui considère cette qualité comme obsolète.',
    genres: ['Action', 'Aventure', 'Science-Fiction'],
    year: 2025,
    rating: 7.4,
    imageId: 'superman-poster',
    videoUrl: 'https://cinecake.xyz/movies/Superman-2025.mp4',
  },
  {
    id: 'elio',
    title: 'Elio',
    description: 'Elio, un petit garçon à l\'imagination débordante, qui se retrouve téléporté par inadvertance dans le Communivers...',
    longDescription: 'Elio, un petit garçon à l\'imagination débordante, qui se retrouve téléporté par inadvertance dans le Communivers, une organisation interplanétaire composée de représentants des galaxies les plus éloignées. Alors que tout l\'univers le considère par erreur comme le chef de la Terre, Elio, loin d\'être préparé à ce genre de pression, va',
    genres: ['Aventure', 'Animation', 'Comédie', 'Familial', 'Science-Fiction'],
    year: 2025,
    rating: 7.0,
    imageId: 'elio-poster',
    videoUrl: 'https://cinecake.xyz/movies/Elio.mp4',
  },
  {
    id: 'mcwalter',
    title: 'McWalter',
    description: 'McWalter, légendaire agent d’élite américain est accusé à tort d’une série d’attentats aux quatre coins du globe.',
    longDescription: 'McWalter, légendaire agent d’élite américain est accusé à tort d’une série d’attentats aux quatre coins du globe. Bien décidé à laver son honneur, il prend la fuite dans le but de résoudre l’énigme, déjouer un complot mondial et sauver la planète…',
    genres: ['Action', 'Aventure', 'Comédie'],
    year: 2025,
    rating: 5.2,
    imageId: 'mcwalter-poster',
    videoUrl: 'https://cinecake.xyz/movies/McWalter.mp4',
  },
  {
    id: 'interstellar',
    title: 'Interstellar',
    description: 'Dans un futur proche, face à une Terre exsangue, un groupe d’explorateurs utilise un vaisseau interstellaire pour franchir un trou de ver permettant de parcourir des distances jusque‐là infranchissables.',
    longDescription: 'Dans un futur proche, face à une Terre exsangue, un groupe d’explorateurs utilise un vaisseau interstellaire pour franchir un trou de ver permettant de parcourir des distances jusque‐là infranchissables. Leur but : trouver un nouveau foyer pour l’humanité.',
    genres: ['Aventure', 'Drame', 'Science-Fiction'],
    year: 2014,
    rating: 8.5,
    imageId: 'interstellar-poster',
    videoUrl: 'https://cinecake.xyz/movies/Interstellar.mp4',
  },
  {
    id: 'destination-finale-bloodlines',
    title: 'Destination finale : Bloodlines',
    description: 'Hantée par un cauchemar terrifiant qui revient sans cesse, Stefanie, étudiante à l’université, rentre chez elle pour retrouver la trace de la seule personne susceptible d’enrayer ce cycle infernal et de sauver ses proches du sort funeste qui les attend…',
    longDescription: 'Hantée par un cauchemar terrifiant qui revient sans cesse, Stefanie, étudiante à l’université, rentre chez elle pour retrouver la trace de la seule personne susceptible d’enrayer ce cycle infernal et de sauver ses proches du sort funeste qui les attend…',
    genres: ['Horreur', 'Mystère'],
    year: 2025,
    rating: 7.1,
    imageId: 'destination-finale-bloodlines-poster',
    videoUrl: 'https://cinecake.xyz/movies/Destination-Finale-Bloodlines.mp4',
  },
  {
    id: 'scream',
    title: 'Scream',
    description: 'Casey Becker, une belle adolescente, est seule dans la maison familiale. Elle s\'apprête à regarder un film d\'horreur, mais le téléphone sonne.',
    longDescription: 'Casey Becker, une belle adolescente, est seule dans la maison familiale. Elle s\'apprête à regarder un film d\'horreur, mais le téléphone sonne. Au bout du fil, un serial killer la malmène, et la force à jouer à un jeu terrible : si elle répond mal à ses questions portant sur les films d\'horreur, celui-ci tuera son copain… Sidney Prescott sait qu\'elle est l\'une des',
    genres: ['Crime', 'Horreur', 'Mystère'],
    year: 1996,
    rating: 7.4,
    imageId: 'scream-poster',
    videoUrl: 'https://cinecake.xyz/movies/Scream.mp4',
  },
  {
    id: 'space-jam',
    title: 'Space Jam',
    description: 'Bugs Bunny et ses amis font appel à une légende du basket pour défier une équipe d\'extraterrestres sur le terrain.',
    longDescription: 'Bugs Bunny et ses amis font appel à une légende du basket pour défier une équipe d\'extraterrestres sur le terrain.',
    genres: ['Aventure', 'Animation', 'Comédie', 'Familial', 'Science-Fiction'],
    year: 1996,
    rating: 6.8,
    imageId: 'space-jam-poster',
    videoUrl: 'https://cinecake.xyz/movies/Space-Jam.mp4',
  },
  {
    id: 'gran-turismo',
    title: 'Gran Turismo',
    description: 'Gran Turismo est inspiré de l\'incroyable histoire vécue d\'une invraisemblable bande d\'infortunés.',
    longDescription: 'Gran Turismo est inspiré de l\'incroyable histoire vécue d\'une invraisemblable bande d\'infortunés – un amateur de jeu vidéo de classe ouvrière, un ex-pilote d\'autos de course paumé et un idéaliste de l\'industrie du sport motorisé. Ensemble, ils risquent tout pour percer dans le sport le plus prestigieux au monde. Gran Turismo est une captivante',
    genres: ['Action', 'Aventure', 'Drame'],
    year: 2023,
    rating: 7.7,
    imageId: 'gran-turismo-poster',
    videoUrl: 'https://cinecake.xyz/movies/Gran-Turismo.mp4',
  },
  {
    id: 'rogue-one-a-star-wars-story',
    title: 'Rogue One : A Star Wars Story',
    description: 'Situé entre les épisodes III et IV de la saga Star Wars, le film nous entraîne aux côtés d’individus ordinaires qui, pour rester fidèles à leurs valeurs, vont tenter l’impossible au péril de leur vie.',
    longDescription: 'Situé entre les épisodes III et IV de la saga Star Wars, le film nous entraîne aux côtés d’individus ordinaires qui, pour rester fidèles à leurs valeurs, vont tenter l’impossible au péril de leur vie. Ils n’avaient pas prévu de devenir des héros, mais dans une époque de plus en plus sombre, ils vont devoir dérober les plans de l’Étoile de la Mort, l’arme de',
    genres: ['Action', 'Aventure', 'Science-Fiction'],
    year: 2016,
    rating: 7.5,
    imageId: 'rogue-one-a-star-wars-story-poster',
    videoUrl: 'https://cinecake.xyz/movies/Rogue-One-A-Star-Wars-Story.mp4',
  },
  {
    id: 'gladiator',
    title: 'Gladiator',
    description: 'Le général romain Maximus est le plus fidèle soutien de l\'empereur Marc Aurèle, qu\'il a conduit de victoire en victoire avec une bravoure et un dévouement exemplaires.',
    longDescription: 'Le général romain Maximus est le plus fidèle soutien de l\'empereur Marc Aurèle, qu\'il a conduit de victoire en victoire avec une bravoure et un dévouement exemplaires. Jaloux du prestige de Maximus, et plus encore de l\'amour que lui voue l\'empereur, le fils de Marc Aurèle, Commode, s\'arroge brutalement le pouvoir, puis ordonne l\'arrestation du général et son exécution. Maximus échappe à ses assassins mais ne peut empêcher le',
    genres: ['Action', 'Aventure', 'Drame'],
    year: 2000,
    rating: 8.2,
    imageId: 'gladiator-poster',
    videoUrl: 'https://cinecake.xyz/movies/Gladiator.mp4',
  },
  {
    id: 'matrix',
    title: 'Matrix',
    description: 'Programmeur anonyme dans un service administratif le jour, Thomas Anderson devient Neo la nuit venue.',
    longDescription: 'Programmeur anonyme dans un service administratif le jour, Thomas Anderson devient Neo la nuit venue. Sous ce pseudonyme, il est l\'un des pirates les plus recherchés du cyber‐espace. À cheval entre deux mondes, Neo est assailli par d\'étranges songes et des messages cryptés provenant d\'un certain Morpheus. Celui‐ci l\'exhorte à aller au‐delà des apparences et à trouver la réponse à la question qui hante constamment ses pensées',
    genres: ['Action', 'Science-Fiction'],
    year: 1999,
    rating: 8.2,
    imageId: 'matrix-poster',
    videoUrl: 'https://cinecake.xyz/movies/Matrix.mp4',
  },
  {
    id: 'titanic',
    title: 'Titanic',
    description: 'Southampton, 10 avril 1912. Le paquebot le plus grand et le plus moderne du monde, réputé pour son insubmersibilité, le « Titanic », appareille pour son premier voyage.',
    longDescription: 'Southampton, 10 avril 1912. Le paquebot le plus grand et le plus moderne du monde, réputé pour son insubmersibilité, le « Titanic », appareille pour son premier voyage. Quatre jours plus tard, il heurte un iceberg. À son bord, un artiste pauvre et une grande bourgeoise tombent amoureux.',
    genres: ['Drame', 'Romance'],
    year: 1997,
    rating: 7.9,
    imageId: 'titanic-poster',
    videoUrl: 'https://cinecake.xyz/movies/Titanic.mp4',
  },
  {
    id: 'top-gun-maverick',
    title: 'Top Gun : Maverick',
    description: 'Après avoir été l’un des meilleurs pilotes de chasse de l\'Aéronavale américaine pendant plus de trente ans, Pete “Maverick" Mitchell continue à repousser ses limites en tant que pilote d\'essai.',
    longDescription: 'Après avoir été l’un des meilleurs pilotes de chasse de l\'Aéronavale américaine pendant plus de trente ans, Pete “Maverick" Mitchell continue à repousser ses limites en tant que pilote d\'essai. Il refuse de monter en grade, car cela l’obligerait à renoncer à voler. Il est chargé de former un détachement de jeunes diplômés de l’école Top Gun pour une',
    genres: ['Action', 'Drame'],
    year: 2022,
    rating: 8.2,
    imageId: 'top-gun-maverick-poster',
    videoUrl: 'https://cinecake.xyz/movies/Top-Gun-Maverick.mp4',
  },
  {
    id: 'oppenheimer',
    title: 'Oppenheimer',
    description: 'En 1942, convaincus que l\'Allemagne hitlérienne est en train de développer une arme nucléaire, les États-Unis initient, dans le plus grand secret, le « Projet Manhattan » destiné à mettre au point la première bombe atomique de l’histoire.',
    longDescription: 'En 1942, convaincus que l\'Allemagne hitlérienne est en train de développer une arme nucléaire, les États-Unis initient, dans le plus grand secret, le « Projet Manhattan » destiné à mettre au point la première bombe atomique de l’histoire. Pour piloter ce dispositif, le gouvernement engage J. Robert Oppenheimer, brillant physicien, qui sera bientôt surnommé « le père de la bombe atomique ». C\'est dans le laboratoire ultra-',
    genres: ['Drame', 'Histoire'],
    year: 2023,
    rating: 8.1,
    imageId: 'oppenheimer-poster',
    videoUrl: 'https://cinecake.xyz/movies/Oppenheimer.mp4',
  },
  {
    id: 'skyfall',
    title: 'Skyfall',
    description: 'Lorsque la dernière mission de Bond tourne mal, plusieurs agents infiltrés se retrouvent exposés dans le monde entier.',
    longDescription: 'Lorsque la dernière mission de Bond tourne mal, plusieurs agents infiltrés se retroutront exposés dans le monde entier. Le MI6 est attaqué, et M est obligée de relocaliser l’Agence. Ces événements ébranlent son autorité, et elle est remise en cause par Mallory, le nouveau président de l’ISC, le comité chargé du renseignement et de la sécurité. Le MI6 est à présent sous le coup d’une double menace, intérieure et extérieure. Il ne reste à',
    genres: ['Action', 'Aventure', 'Thriller'],
    year: 2012,
    rating: 7.3,
    imageId: 'skyfall-poster',
    videoUrl: 'https://cinecake.xyz/movies/Skyfall.mp4',
  },
  {
    id: 'zack-snyders-justice-league',
    title: 'Zack Snyder\'s Justice League',
    description: 'Bruce Wayne est déterminé à faire en sorte que le sacrifice ultime de Superman ne soit pas vain.',
    longDescription: 'Bruce Wayne est déterminé à faire en sorte que le sacrifice ultime de Superman ne soit pas vain. Pour cela, avec l\'aide de Diana Prince, il met en place un plan pour recruter une équipe de métahumains afin de protéger le monde d\'une menace apocalyptique imminente. La tâche s\'avère plus difficile qu\'il ne l\'imaginait, car chacune des recrues',
    genres: ['Action', 'Aventure', 'Fantastique'],
    year: 2021,
    rating: 8.1,
    imageId: 'zack-snyders-justice-league-poster',
    videoUrl: 'https://cinecake.xyz/movies/Zack-Snyders-Justice-League.mp4',
  },
  {
    id: 'the-dark-knight',
    title: 'The Dark Knight : Le Chevalier noir',
    description: 'Batman aborde une phase décisive de sa guerre contre le crime à Gotham City.',
    longDescription: 'Batman aborde une phase décisive de sa guerre contre le crime à Gotham City. Avec l\'aide du lieutenant de police Jim Gordon et du nouveau procureur Harvey Dent, il entreprend de démanteler les dernières organisations criminelles qui infestent les rues de la ville. L\'association s\'avère efficace, mais le trio se heurte bientôt à un nouveau génie',
    genres: ['Action', 'Crime', 'Drame', 'Thriller'],
    year: 2008,
    rating: 8.5,
    imageId: 'the-dark-knight-poster',
    videoUrl: 'https://cinecake.xyz/movies/The-Dark-Knight-Le-Chevalier-noir.mp4',
  }
];
