import type { Movie } from '@/lib/types';

export const movies: Movie[] = [
  {
    id: 'f1-le-film',
    title: 'F1® Le Film',
    description: 'Sonny Hayes était le prodige de la F1 des années 90 jusqu’à son terrible accident.',
    longDescription: 'Sonny Hayes était le prodige de la F1 des années 90 jusqu’à son terrible accident. Trente ans plus tard, devenu un pilote indépendant, il est contacté par Ruben Cervantes, patron d’une écurie en faillite qui le convainc de revenir pour sauver l’équipe et prouver qu’il est toujours le meilleur. Aux côtés de Joshua Pearce, diamant brut prêt à devenir le numéro 1, Sonny réalise vite qu\'en F1, son coéquipier est aussi son plus grand rival.',
    genres: ['Action', 'Drame'],
    year: 2025,
    rating: 8.7,
    imageId: 'f1-le-film-poster',
    videoUrl: 'https://cinecake.xyz/movies/F1-The-Movie.mp4',
  },
  {
    id: 'super-mario-bros-le-film',
    title: 'Super Mario Bros. le film',
    description: 'Alors qu’ils tentent de réparer une canalisation souterraine, Mario et son frère Luigi, tous deux plombiers, se retrouvent plongés dans un nouvel univers féerique à travers un mystérieux conduit.',
    longDescription: 'Alors qu’ils tentent de réparer une canalisation souterraine, Mario et son frère Luigi, tous deux plombiers, se retrouvent plongés dans un nouvel univers féerique à travers un mystérieux conduit. Mais lorsque les deux frères sont séparés, Mario s’engage dans une aventure trépidante pour retrouver Luigi. Dans sa quête, il peut compter sur l’aide du champignon Toad, habitant du Royaume Champignon, et les conseils avisés.',
    genres: ['Aventure', 'Animation', 'Comédie', 'Familial', 'Fantastique'],
    year: 2023,
    rating: 7.6,
    imageId: 'super-mario-bros-le-film-poster',
    videoUrl: 'https://cinecake.xyz/movies/Super-Mario-Bros-Le-Film.mp4',
  },
  {
    id: 'mission-impossible-final-reckoning',
    title: 'Mission : Impossible - The Final Reckoning',
    description: 'Ethan Hunt se rend à Londres avec son équipe dans l\'espoir de remonter la piste du mystérieux Gabriel.',
    longDescription: 'Ethan Hunt se rend à Londres avec son équipe dans l\'espoir de remonter la piste du mystérieux Gabriel, qu\'il a affronté deux mois auparavant à bord de l\'Orient-Express et qui détient la clé contrôlant l’intelligence artificielle toute puissante surnommée l\'Entité. Adulée par les uns, redoutée par les autres, l’Entité se distingue par sa capacité à prédire',
    genres: ['Action', 'Aventure', 'Thriller'],
    year: 2025,
    rating: 7.3,
    imageId: 'mission-impossible-final-reckoning-poster',
    videoUrl: 'https://cinecake.xyz/movies/Mission-Impossible-The-Final-Reckoning.mp4',
  },
  {
    id: 'superman',
    title: 'Superman',
    description: 'Superman doit trouver l’équilibre entre ses racines kryptoniennes et son identité humaine...',
    longDescription: 'Superman doit trouver l’équilibre entre ses racines kryptoniennes et son identité humaine, sous les traits de Clark Kent, originaire de Smallville, dans le Kansas. Il est l’incarnation de la vérité, de la justice et des valeurs américaines et il est animé par une véritable bienveillance dans un monde qui considère cette qualité comme obsolète.',
    genres: ['Action', 'Aventure', 'Science-Fiction'],
    year: 2025,
    rating: 7.4,
    imageId: 'superman-poster',
    videoUrl: 'https://cinecake.xyz/movies/Superman-2025.mp4',
  },
  {
    id: 'elio',
    title: 'Elio',
    description: 'Elio, un petit garçon à l\'imagination débordante, qui se retrouve téléporté par inadvertance dans le Communivers...',
    longDescription: 'Elio, un petit garçon à l\'imagination débordante, qui se retrouve téléporté par inadvertance dans le Communivers, une organisation interplanétaire composée de représentants des galaxies les plus éloignées. Alors que tout l\'univers le considère par erreur comme le chef de la Terre, Elio, loin d\'être préparé à ce genre de pression, va',
    genres: ['Aventure', 'Animation', 'Comédie', 'Familial', 'Science-Fiction'],
    year: 2025,
    rating: 7.0,
    imageId: 'elio-poster',
    videoUrl: 'https://cinecake.xyz/movies/Elio.mp4',
  },
  {
    id: 'mcwalter',
    title: 'McWalter',
    description: 'McWalter, légendaire agent d’élite américain est accusé à tort d’une série d’attentats aux quatre coins du globe.',
    longDescription: 'McWalter, légendaire agent d’élite américain est accusé à tort d’une série d’attentats aux quatre coins du globe. Bien décidé à laver son honneur, il prend la fuite dans le but de résoudre l’énigme, déjouer un complot mondial et sauver la planète…',
    genres: ['Action', 'Aventure', 'Comédie'],
    year: 2025,
    rating: 5.2,
    imageId: 'mcwalter-poster',
    videoUrl: 'https://cinecake.xyz/movies/McWalter.mp4',
  },
  {
    id: 'interstellar',
    title: 'Interstellar',
    description: 'Dans un futur proche, face à une Terre exsangue, un groupe d’explorateurs utilise un vaisseau interstellaire pour franchir un trou de ver permettant de parcourir des distances jusque‐là infranchissables.',
    longDescription: 'Dans un futur proche, face à une Terre exsangue, un groupe d’explorateurs utilise un vaisseau interstellaire pour franchir un trou de ver permettant de parcourir des distances jusque‐là infranchissables. Leur but : trouver un nouveau foyer pour l’humanité.',
    genres: ['Aventure', 'Drame', 'Science-Fiction'],
    year: 2014,
    rating: 8.5,
    imageId: 'interstellar-poster',
    videoUrl: 'https://cinecake.xyz/movies/Interstellar.mp4',
  },
  {
    id: 'destination-finale-bloodlines',
    title: 'Destination finale : Bloodlines',
    description: 'Hantée par un cauchemar terrifiant qui revient sans cesse, Stefanie, étudiante à l’université, rentre chez elle pour retrouver la trace de la seule personne susceptible d’enrayer ce cycle infernal et de sauver ses proches du sort funeste qui les attend…',
    longDescription: 'Hantée par un cauchemar terrifiant qui revient sans cesse, Stefanie, étudiante à l’université, rentre chez elle pour retrouver la trace de la seule personne susceptible d’enrayer ce cycle infernal et de sauver ses proches du sort funeste qui les attend…',
    genres: ['Horreur', 'Mystère'],
    year: 2025,
    rating: 7.1,
    imageId: 'destination-finale-bloodlines-poster',
    videoUrl: 'https://cinecake.xyz/movies/Destination-Finale-Bloodlines.mp4',
  },
  {
    id: 'scream',
    title: 'Scream',
    description: 'Casey Becker, une belle adolescente, est seule dans la maison familiale. Elle s\'apprête à regarder un film d\'horreur, mais le téléphone sonne.',
    longDescription: 'Casey Becker, une belle adolescente, est seule dans la maison familiale. Elle s\'apprête à regarder un film d\'horreur, mais le téléphone sonne. Au bout du fil, un serial killer la malmène, et la force à jouer à un jeu terrible : si elle répond mal à ses questions portant sur les films d\'horreur, celui-ci tuera son copain… Sidney Prescott sait qu\'elle est l\'une des',
    genres: ['Crime', 'Horreur', 'Mystère'],
    year: 1996,
    rating: 7.4,
    imageId: 'scream-poster',
    videoUrl: 'https://cinecake.xyz/movies/Scream.mp4',
  },
  {
    id: 'space-jam',
    title: 'Space Jam',
    description: 'Bugs Bunny et ses amis font appel à une légende du basket pour défier une équipe d\'extraterrestres sur le terrain.',
    longDescription: 'Bugs Bunny et ses amis font appel à une légende du basket pour défier une équipe d\'extraterrestres sur le terrain.',
    genres: ['Aventure', 'Animation', 'Comédie', 'Familial', 'Science-Fiction'],
    year: 1996,
    rating: 6.8,
    imageId: 'space-jam-poster',
    videoUrl: 'https://cinecake.xyz/movies/Space-Jam.mp4',
  },
  {
    id: 'gran-turismo',
    title: 'Gran Turismo',
    description: 'Gran Turismo est inspiré de l\'incroyable histoire vécue d\'une invraisemblable bande d\'infortunés.',
    longDescription: 'Gran Turismo est inspiré de l\'incroyable histoire vécue d\'une invraisemblable bande d\'infortunés – un amateur de jeu vidéo de classe ouvrière, un ex-pilote d\'autos de course paumé et un idéaliste de l\'industrie du sport motorisé. Ensemble, ils risquent tout pour percer dans le sport le plus prestigieux au monde. Gran Turismo est une captivante',
    genres: ['Action', 'Aventure', 'Drame'],
    year: 2023,
    rating: 7.7,
    imageId: 'gran-turismo-poster',
    videoUrl: 'https://cinecake.xyz/movies/Gran-Turismo.mp4',
  },
  {
    id: 'rogue-one-a-star-wars-story',
    title: 'Rogue One : A Star Wars Story',
    description: 'Situé entre les épisodes III et IV de la saga Star Wars, le film nous entraîne aux côtés d’individus ordinaires qui, pour rester fidèles à leurs valeurs, vont tenter l’impossible au péril de leur vie.',
    longDescription: 'Situé entre les épisodes III et IV de la saga Star Wars, le film nous entraîne aux côtés d’individus ordinaires qui, pour rester fidèles à leurs valeurs, vont tenter l’impossible au péril de leur vie. Ils n’avaient pas prévu de devenir des héros, mais dans une époque de plus en plus sombre, ils vont devoir dérober les plans de l’Étoile de la Mort, l’arme de',
    genres: ['Action', 'Aventure', 'Science-Fiction'],
    year: 2016,
    rating: 7.5,
    imageId: 'rogue-one-a-star-wars-story-poster',
    videoUrl: 'https://cinecake.xyz/movies/Rogue-One-A-Star-Wars-Story.mp4',
  },
  {
    id: 'gladiator',
    title: 'Gladiator',
    description: 'Le général romain Maximus est le plus fidèle soutien de l\'empereur Marc Aurèle, qu\'il a conduit de victoire en victoire avec une bravoure et un dévouement exemplaires.',
    longDescription: 'Le général romain Maximus est le plus fidèle soutien de l\'empereur Marc Aurèle, qu\'il a conduit de victoire en victoire avec une bravoure et un dévouement exemplaires. Jaloux du prestige de Maximus, et plus encore de l\'amour que lui voue l\'empereur, le fils de Marc Aurèle, Commode, s\'arroge brutalement le pouvoir, puis ordonne l\'arrestation du général et son exécution. Maximus échappe à ses assassins mais ne peut empêcher le',
    genres: ['Action', 'Aventure', 'Drame'],
    year: 2000,
    rating: 8.2,
    imageId: 'gladiator-poster',
    videoUrl: 'https://cinecake.xyz/movies/Gladiator.mp4',
  },
  {
    id: 'matrix',
    title: 'Matrix',
    description: 'Programmeur anonyme dans un service administratif le jour, Thomas Anderson devient Neo la nuit venue.',
    longDescription: 'Programmeur anonyme dans un service administratif le jour, Thomas Anderson devient Neo la nuit venue. Sous ce pseudonyme, il est l\'un des pirates les plus recherchés du cyber‐espace. À cheval entre deux mondes, Neo est assailli par d\'étranges songes et des messages cryptés provenant d\'un certain Morpheus. Celui‐ci l\'exhorte à aller au‐delà des apparences et à trouver la réponse à la question qui hante constamment ses pensées',
    genres: ['Action', 'Science-Fiction'],
    year: 1999,
    rating: 8.2,
    imageId: 'matrix-poster',
    videoUrl: 'https://cinecake.xyz/movies/Matrix.mp4',
  },
  {
    id: 'titanic',
    title: 'Titanic',
    description: 'Southampton, 10 avril 1912. Le paquebot le plus grand et le plus moderne du monde, réputé pour son insubmersibilité, le « Titanic », appareille pour son premier voyage.',
    longDescription: 'Southampton, 10 avril 1912. Le paquebot le plus grand et le plus moderne du monde, réputé pour son insubmersibilité, le « Titanic », appareille pour son premier voyage. Quatre jours plus tard, il heurte un iceberg. À son bord, un artiste pauvre et une grande bourgeoise tombent amoureux.',
    genres: ['Drame', 'Romance'],
    year: 1997,
    rating: 7.9,
    imageId: 'titanic-poster',
    videoUrl: 'https://cinecake.xyz/movies/Titanic.mp4',
  },
  {
    id: 'top-gun-maverick',
    title: 'Top Gun : Maverick',
    description: 'Après avoir été l’un des meilleurs pilotes de chasse de l\'Aéronavale américaine pendant plus de trente ans, Pete “Maverick" Mitchell continue à repousser ses limites en tant que pilote d\'essai.',
    longDescription: 'Après avoir été l’un des meilleurs pilotes de chasse de l\'Aéronavale américaine pendant plus de trente ans, Pete “Maverick" Mitchell continue à repousser ses limites en tant que pilote d\'essai. Il refuse de monter en grade, car cela l’obligerait à renoncer à voler. Il est chargé de former un détachement de jeunes diplômés de l’école Top Gun pour une',
    genres: ['Action', 'Drame'],
    year: 2022,
    rating: 8.2,
    imageId: 'top-gun-maverick-poster',
    videoUrl: 'https://cinecake.xyz/movies/Top-Gun-Maverick.mp4',
  },
  {
    id: 'cosmic-odyssey',
    title: 'Cosmic Odyssey',
    description: 'A journey through space and time.',
    longDescription: 'In the year 2242, a team of astronauts embarks on a perilous journey to a newly discovered wormhole, hoping to find a new home for humanity. What they find is beyond their wildest imagination, challenging their understanding of the universe and their own existence.',
    genres: ['Sci-Fi', 'Adventure'],
    year: 2023,
    rating: 8.5,
    imageId: 'cosmic-odyssey-poster',
  },
  {
    id: 'neon-shadows',
    title: 'Neon Shadows',
    description: 'A detective story in a futuristic city.',
    longDescription: 'In the rain-slicked, neon-lit streets of Neo-Kyoto, a hard-boiled detective hunts a cybernetic killer. As he delves deeper into the city\'s underworld, he uncovers a conspiracy that reaches the highest echelons of power.',
    genres: ['Cyberpunk', 'Thriller', 'Mystery'],
    year: 2022,
    rating: 7.9,
    imageId: 'neon-shadows-poster',
  },
  {
    id: 'the-last-kingdom',
    title: 'The Last Kingdom',
    description: 'An epic tale of a forgotten king.',
    longDescription: 'In an age of myths and legends, a displaced prince must reclaim his birthright and unite a fractured kingdom against a rising darkness. His path is fraught with magic, monsters, and betrayal.',
    genres: ['Fantasy', 'Action'],
    year: 2021,
    rating: 8.2,
    imageId: 'the-last-kingdom-poster',
  },
  {
    id: 'echoes-of-time',
    title: 'Echoes of Time',
    description: 'A love story that transcends time.',
    longDescription: 'A historian discovers a 19th-century diary and finds herself communicating with its author across time. Their impossible connection blossoms into a romance that defies the laws of physics, but a dark secret threatens to tear them apart forever.',
    genres: ['Romance', 'Drama', 'Sci-Fi'],
    year: 2024,
    rating: 8.8,
    imageId: 'echoes-of-time-poster',
  },
  {
    id: 'zero-gravity',
    title: 'Zero Gravity',
    description: 'An adrenaline-fueled race in space.',
    longDescription: 'The galaxy\'s most daring pilots compete in the "Zero-G" championship, a high-stakes race through treacherous asteroid fields and alien-made structures. For one rookie pilot, winning is not just about glory, but about saving her family.',
    genres: ['Sci-Fi', 'Action', 'Sports'],
    year: 2023,
    rating: 7.5,
    imageId: 'zero-gravity-poster',
  },
  {
    id: 'the-manhattan-project',
    title: 'The Manhattan Project',
    description: 'A tense thriller about a stolen blueprint.',
    longDescription: 'During the Cold War, a brilliant but disgraced physicist is framed for stealing nuclear secrets. He must race against time to clear his name and prevent a catastrophic attack, with both the CIA and KGB on his tail.',
    genres: ['Thriller', 'Spy', 'Drama'],
    year: 2020,
    rating: 7.6,
    imageId: 'manhattan-project-poster',
  },
  {
    id: 'sunken-city',
    title: 'Sunken City',
    description: 'An adventure to find a lost civilization.',
    longDescription: 'A team of deep-sea explorers discovers a map leading to the legendary city of Atlantis. Their expedition faces immense dangers from the crushing depths, mythical creatures, and a rival corporation that wants the city\'s power for itself.',
    genres: ['Adventure', 'Action'],
    year: 2022,
    rating: 7.1,
    imageId: 'sunken-city-poster',
  },
  {
    id: 'the-comedian',
    title: 'The Comedian',
    description: 'The rise and fall of a stand-up comic.',
    longDescription: 'A struggling stand-up comedian finally gets his big break, but the pressures of fame, a crumbling personal life, and his inner demons threaten to bring his world crashing down just as he reaches the top.',
    genres: ['Drama', 'Comedy'],
    year: 2021,
    rating: 8.4,
    imageId: 'the-comedian-poster',
  },
  {
    id: 'mind-heist',
    title: 'Mind Heist',
    description: 'Stealing ideas is a dangerous game.',
    longDescription: 'In a world where thoughts can be extracted, a corporate spy specializes in stealing secrets directly from the minds of executives. His latest job is his most dangerous: to plant an idea instead of stealing one.',
    genres: ['Sci-Fi', 'Thriller'],
    year: 2019,
    rating: 8.7,
    imageId: 'mind-heist-poster',
  },
  {
    id: 'wildlands',
    title: 'Wildlands',
    description: 'A story of survival in the untamed wilderness.',
    longDescription: 'After a plane crash in the vast Alaskan wilderness, a lone survivor must battle the elements, hunger, and predators to make her way back to civilization, armed with only her wits and the will to live.',
    genres: ['Survival', 'Drama', 'Adventure'],
    year: 2023,
    rating: 8.0,
    imageId: 'wildlands-poster',
  },
  {
    id: 'the-clockwork-enigma',
    title: 'The Clockwork Enigma',
    description: 'A Victorian-era mystery.',
    longDescription: 'London, 1888. A brilliant inventor is found murdered, a strange clockwork device clutched in his hand. A consulting detective and his loyal partner must unravel the enigma, leading them into a world of secret societies and automatons.',
    genres: ['Mystery', 'Steampunk'],
    year: 2022,
    rating: 7.8,
    imageId: 'clockwork-enigma-poster',
  },
  {
    id: 'red-planet-rebellion',
    title: 'Red Planet Rebellion',
    description: 'The fight for Mars\' independence.',
    longDescription: 'The first generation of Martian colonists, born and raised on the Red Planet, rise up against an oppressive Earth-based corporation that controls their air, water, and future. A young revolutionary leader emerges to lead the fight for a free Mars.',
    genres: ['Sci-Fi', 'Action', 'War'],
    year: 2024,
    rating: 8.1,
    imageId: 'red-planet-rebellion-poster',
  },
];

    

    
